export const ACCESS_TOKEN_REQUEST = "ACCESS_TOKEN_REQUEST"
export const ACCESS_TOKEN_SUCCESS = "ACCESS_TOKEN_SUCCESS"
export const ACCESS_TOKEN_ERROR = "ACCESS_TOKEN_ERROR"
export const ACCESS_TOKEN_NOTFOUND = "ACCESS_TOKEN_NOTFOUND"

export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"

export const USER_OTP_REQUEST = "USER_OTP_REQUEST"
export const USER_OTP_SUCCESS = "USER_OTP_SUCCESS"
export const USER_OTP_FAIL = "USER_OTP_FAIL"

export const USER_OTP_VERIFY_REQUEST = "USER_OTP_VERIFY_REQUEST"
export const USER_OTP_VERIFY_SUCCESS = "USER_OTP_VERIFY_SUCCESS"
export const USER_OTP_VERIFY_FAIL = "USER_OTP_VERIFY_FAIL"

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST"
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"

export const CLOUD_PASSWORD_REQUEST = "CLOUD_PASSWORD_REQUEST"
export const CLOUD_PASSWORD_SUCCESS = "CLOUD_PASSWORD_SUCCESS"
export const CLOUD_PASSWORD_FAIL = "CLOUD_PASSWORD_FAIL"

export const FORGET_CLOUD_PASSWORD_REQUEST = "FORGET_CLOUD_PASSWORD_REQUEST"
export const FORGET_CLOUD_PASSWORD_SUCCESS = "FORGET_CLOUD_PASSWORD_SUCCESS"
export const FORGET_CLOUD_PASSWORD_FAIL = "FORGET_CLOUD_PASSWORD_FAIL"

export const RESET_CLOUD_PASSWORD_REQUEST = "RESET_CLOUD_PASSWORD_REQUEST"
export const RESET_CLOUD_PASSWORD_SUCCESS = "RESET_CLOUD_PASSWORD_SUCCESS"
export const RESET_CLOUD_PASSWORD_FAIL = "RESET_CLOUD_PASSWORD_FAIL"

export const USER_MOBILE_PAGE = "USER_MOBILE_PAGE"
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGOUT = "USER_LOGOUT"