export const GET_USER_REQUEST = "GET_USER_REQUEST"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_ERROR = "GET_USER_ERROR"
export const CLEAR_USER_INFO = "CLEAR_USER_INFO"

export const USER_SOCKET_CONNECT = "USER_SOCKET_CONNECT"
export const USER_SOCKET_DISCONNECT = "USER_SOCKET_DISCONNECT"