export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";

export const GET_USER_INBOXES_REQUEST = "GET_USER_INBOXES_REQUEST";
export const GET_USER_INBOXES_SUCCESS = "GET_USER_INBOXES_SUCCESS";
export const GET_USER_INBOXES_FAIL = "GET_USER_INBOXES_FAIL";
export const NEW_INBOX_ARRIVED = "NEW_INBOX_ARRIVED";
export const CLEAR_USER_INBOXES = "CLEAR_USER_INBOXES";

export const GET_USER_CHAT_REQUEST = "GET_USER_CHAT_REQUEST";
export const GET_USER_CHAT_SUCCESS = "GET_USER_CHAT_SUCCESS";
export const GET_USER_CHAT_FAIL = "GET_USER_CHAT_FAIL";
export const CLEAR_USER_CHAT = "CLEAR_USER_CHAT";

export const SET_SENDER_DATA = "SET_SENDER_DATA";
export const GET_CHAT_REQUEST = "GET_CHAT_REQUEST";
export const GET_CHAT_SUCCESS = "GET_CHAT_SUCCESS";
export const GET_CHAT_FAIL = "GET_CHAT_FAIL";
export const CLEAR_CHAT_INFO = "CLEAR_CHAT_INFO";

export const GET_GROUP_CHAT_REQUEST = "GET_GROUP_CHAT_REQUEST";
export const GET_GROUP_CHAT_SUCCESS = "GET_GROUP_CHAT_SUCCESS";
export const GET_GROUP_CHAT_FAIL = "GEGROUP_CHAT_FAIL";
export const CLEAR_GROUP_CHAT = "CLEAR_GROUP_CHAT";

export const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAIL = "GET_SEARCH_FAIL";
export const CLEAR_SEARCH_INFO = "CLEAR_SEARCH_INFO";

export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL";

export const SENDED_MSG_SUCCESS = "SENDED_MSG_SUCCESS";
export const RECIEVED_MSG_SUCCESS = "RECIEVED_MSG_SUCCESS";
export const SENDED_MSG_FAIL = "SENDED_MSG_FAIL";